import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { OrderItem } from "./orderService";

export interface DispatchResponse {
  supplierId: string;
  supplierName: string;
  status: "success" | "failed";
  pdfBlob?: Blob;
}

export const DispatchService = {
  /**
   * Main entry point for dispatching orders to suppliers
   */
  async dispatchOrders(orderId: string, items: OrderItem[]): Promise<DispatchResponse[]> {
    // 1. Group items by supplier
    const groups = items.reduce((acc, item) => {
      const sName = item.supplier_name || "General Supply Co.";
      if (!acc[sName]) acc[sName] = [];
      acc[sName].push(item);
      return acc;
    }, {} as Record<string, OrderItem[]>);

    const results: DispatchResponse[] = [];

    // 2. Process each supplier group
    for (const [sName, supplierItems] of Object.entries(groups)) {
      try {
        const pdfBlob = await this.generateOrderPDF(orderId, sName, supplierItems);
        
        // Mocking API call to SendGrid/Twilio
        console.log(`[Dispatch] Sending PDF to ${sName} via Email...`);
        await new Promise(resolve => setTimeout(resolve, 800)); // Simulate network

        results.push({
          supplierId: sName,
          supplierName: sName,
          status: "success",
          pdfBlob
        });
      } catch (error) {
        console.error(`Dispatch failed for ${sName}:`, error);
        results.push({
          supplierId: sName,
          supplierName: sName,
          status: "failed"
        });
      }
    }

    return results;
  },

  /**
   * Generate a professional PDF document for the supplier
   */
  async generateOrderPDF(orderId: string, supplierName: string, items: OrderItem[]): Promise<Blob> {
    const doc = new jsPDF() as any;
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(138, 43, 226); // Vanguard Primary Color
    doc.text("VANGUARD ALLIANCE", 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Elite Solopreneur Supply Routing Network", 14, 28);
    
    // Order Info
    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.text(`Order ID: ${orderId.substring(0, 8)}`, 14, 45);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 52);
    doc.text(`Recipient: ${supplierName}`, 14, 59);

    // Table
    const tableData = items.map(item => [item.name, item.quantity]);
    
    doc.autoTable({
      startY: 70,
      head: [['Product Name', 'Quantity']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [138, 43, 226] },
      margin: { top: 70 },
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY || 150;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("This order was automatically generated by the Vanguard Engine.", 14, finalY + 20);
    doc.text("Thank you for your service to the Alliance.", 14, finalY + 27);

    return doc.output('blob');
  }
};
